"""single embedding test"""

# from openai import OpenAI

# client = OpenAI()

# def generate_embedding(text):
#     response = client.embeddings.create(
#         model =  "text-embedding-3-small",
#         input = text
#     )

#     return response.data[0].embedding


# text = "Derivative trades require a UTI."

# embedding = generate_embedding(text)

# print(type(embedding))
# print(len(embedding))
# print(embedding[:10])

"""batch embedding and search test"""

from openai import OpenAI
import numpy as np

client = OpenAI()


# Generates embeddings for multiple pieces of text in one API request.
def generate_embeddings(texts):

    response = client.embeddings.create(
        model="text-embedding-3-small",
        input=texts
    )

    return [item.embedding for item in response.data]


# Calculates how similar two embedding vectors are.
def cosine_similarity(vector_a, vector_b):

    return np.dot(vector_a, vector_b) / (
        np.linalg.norm(vector_a) * np.linalg.norm(vector_b)
    )


# Dummy document chunks
chunks = [
    "Derivative trades require a UTI.",
    "Equity trades require a valid LEI.",
    "Trade amounts must be greater than zero.",
    "Employees must complete annual compliance training."
]


# Generate embeddings for all document chunks in one API request.
chunk_embeddings = generate_embeddings(chunks)

# User question
question = "What identifier is needed for derivative reporting?"


# Generate an embedding for the question.
# generate_embeddings expects a list, so we pass [question].
# [0] extracts the single embedding returned.
question_embedding = generate_embeddings([question])[0]


# Store each chunk together with its similarity score.
results = []

for chunk, embedding in zip(chunks, chunk_embeddings):

    similarity = cosine_similarity(
        question_embedding,
        embedding
    )

    results.append(
        {
            "chunk": chunk,
            "similarity": similarity
        }
    )


# Rank chunks from highest similarity to lowest.
results.sort(
    key=lambda result: result["similarity"],
    reverse=True
)


# Retrieve the Top-K most relevant chunks.
top_k = 2
retrieved_chunks = results[:top_k]

#Provides context and question to the LLM to generate a grounded answer
def generate_answer(question, retrieved_chunks):
    context = ""
    for result in retrieved_chunks:
        context += result["chunk"]

    response = client.responses.create(
        model = "gpt-5.6-luna",

        instructions="""
        You are a regulatory reporting assistant.

        Answer the question using only the provided context.
        If the context does not contain enough information,
        state that the available context is insufficient.
        Do not invent regulatory requirements.
        """,

        input = f"""Context :
        {context}

        question = {question}"""
    )

    return response.output_text

# Prints the response generated by LLM
answer = generate_answer(
    question,
    retrieved_chunks
)

print("ANSWER:")
print(answer)